### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by shrimpwagon** [avadev/AvaTax-REST-V2-JRE-SDK#1]
Getting this error today:

Result: Error
Error Details: null
Error Summary: The byte 0x13 is not valid at this location.  Line 35, position 19.
Error Source: Avalara.Web.REST

My guess is that we are using version 1. I integrated the Java API over a year ago.

Was there a major change to the API server yesterday/today? Are you still supporting version 1 API?

**Comment by drheart** [comment]
Hi there, apologies for the delay in reply. It looks like I'm not getting notifications for issues on this repo. If you created an integration with the Java API over a year ago, you were definitely using the version 1 REST API. We still support that version, and there has not been a change to that endpoint. I'd be happy to help you troubleshoot, if you're still experiencing issues.

**Comment by shrimpwagon** [comment]
I'm still having this issue. I have no clue what this is. My guess is that we are sending some invalid character. I will need to look at the log of this request and see the raw data sent.
