### ISSUE TITLE
Client.createTransaction ignores transaction date format and throws com.google.gson.JsonSyntaxException

### ISSUE THREAD

**Issue by SimoneMSR** [avadev/AvaTax-REST-V2-JRE-SDK#10]
The problem arises because the response from Avalara in the TransactionModel serialized representation contains a string for the field **date** which has a strange format, which cannot generate a Date object
{
   "id":0,
   "code":"237418ae-54b5-456d-ae4d-339465bb9b4e",
   "companyId":0,
   **"date":"2017-07-13"**,
   "paymentDate":"2017-07-13",
   .
   .
   .
}

**Comment by SimoneMSR** [comment]
I would suggest to substitute all Date fields in any model class with String fields (the problem exists also in TransactionLineModel, for example)

**Comment by payne8** [comment]
I am experiencing this issue as well. When can we expect a resolution to this?

**Comment by payne8** [comment]
I figured out that we were using an older version of Gson which was having a hard time serializing and deserializing the Date objects in the format that AvaTax API wants/sends them in. Updating Gson made the requests start working.

**Comment by SimoneMSR** [comment]
Wow, interesting. Could you post the Gson version that solved your problem?

**Comment by payne8** [comment]
Version 2.8.1 fixed it.

We were on v2.2.2 previously.

**Comment by drheart** [comment]
The version of Gson used in prior builds was 2.8.0, but I have bumped it to 2.8.2 in c6b470316. Since 2.8.1 appears to have resolved the issue, I'll go ahead and close this out.
