### ISSUE TITLE
Transaction calls are not returning the result with version 20.12

### ISSUE THREAD

**Issue by krishnaswami-rajagopalan** [avadev/AvaTax-REST-V2-JRE-SDK#115]
Team:
Thank you for your massive work on providing the SDK.

[TestTransaction.txt](https://github.com/avadev/AvaTax-REST-V2-JRE-SDK/files/7813647/TestTransaction.txt)

We have been using the Java SDK for Avatax. We wanted to upgrade from version 20.10 to 20.12

But we are facing the following issue

The transactions are getting created in the Avalara side, but SDK does not get the result of the REST call from Avalara side. Till Version 20.10 we never faced this issue. From my Analysis In the code RestCall.java line 152 is false and so TransactionModel is not getting returned.

I am attaching the test code:
Please replace the Username, Password and Avalara Company Code in the code.

Thank you for all your help.
Krishna

**Comment by avasachinbaijal** [comment]
Hi @krishnaswami-rajagopalan , 
We are looking into the issue and able to reproduce it. The fix will be deployed as part of next release.
Thanks,
Sachin

**Comment by avasachinbaijal** [comment]
Hi @krishnaswami-rajagopalan ,

The issue reported is fixed and released (version: 21.12.1); please verify and let us know if you have any observation.

Thanks,
Sachin

**Comment by krishnaswami-rajagopalan** [comment]
@avasachinbaijal Thank you for the quick response. I will check and give my feedback. 

Krishnaswami
from SmartERP

**Comment by krishnaswami-rajagopalan** [comment]
@avasachinbaijal It is working. I tested the code that I had attached and could get the results. We will test all the processes such and get back to you.
