### ISSUE TITLE
It's not possible to confugure/change thread pool.

### ISSUE THREAD

**Issue by Tapac** [avadev/AvaTax-REST-V2-JRE-SDK#4]
We have to configure AvaTaxClient thread pool size and gracefully shutdown it, but in current implementation it's unreachable.
Also it's not possible to configure httpClient options (timeouts, etc).

Could you please extend current api to allow provide custom executor and HttpClientBuilder for RestCallFactory ?

**Comment by drheart** [comment]
Sure thing! We've got a release coming up in about two weeks, so this should appear in the -SNAPSHOT repo before then.

**Comment by drheart** [comment]
Hi @Tapac,

The requested features plus a few more items have been merged into the latest development branch and are published as part of our SNAPSHOT release (17.12.0.147-SNAPSHOT), which also includes support for the new features of the 17.12 API.

Best regards,


Dustin R. Heart

**Comment by drheart** [comment]
In addition, this release will be published as a final release once it passes our internal test suite.
