### ISSUE TITLE
New TransactionBuilder function to set line number

### ISSUE THREAD

**Issue by ted-spence-avalara** [avadev/AvaTax-REST-V2-JRE-SDK#8]
Please add an overloaded function to `WithLine()` that allows a user to choose their line number, as per this comment thread:

https://community.avalara.com/avalara/topics/line-number-seems-to-be-open-on-api-but-forced-to-auto-increment-value-in-java-sdk

**Comment by mikegellis** [comment]
Can this also be done for the .net SDK?
